---
services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: ["server", "/data", "--console-address", ":9201", "--address", ":9200"]
    #privileged: true
    environment:
      - MINIO_ROOT_USER=${ADMIN:-admin}
      - MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD
    volumes:
      - ./data:/data
    ports:
      - 9200:9200
      - 9201:9201
    restart: unless-stopped
    # Uncomment following to enable Traefik:
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.services.minio.loadbalancer.server.port=9000
    #   - traefik.docker.network=proxy
#     networks:
#       - proxy

# networks:
#   proxy:
#     driver: bridge
#     external: true
